name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  issue-create:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: run task
      run: |
            gem install faraday -v 0.9.2
            gem install activesupport
            gem install sitemap-parser

            ruby issue-create.rb