name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  issue-create:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.8
    - name: run install depencencies
      run: |
            gem install faraday
            gem install activesupport
            gem install sitemap-parser 
    - name: run command
      run: |
            ruby issue-create.rb